source 'https://rubygems.org'

gem 'rails', '~>3.0.20'

gem 'rake', '~>10.1.1'
gem 'minitest', '~>4.7.5'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

gem 'newrelic_rpm', :path => '../../..'

if (RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", '1.2.5'
  gem "activerecord-jdbcsqlite3-adapter", '1.2.5'
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3-ruby"
end

gem 'pry', '~> 0.9.12'
