source 'http://rubygems.org'

gem 'test-unit'
gem 'rails', '~>3.0.20'
gem 'newrelic_rpm', :path => '../../..'
gem "mocha"
gem 'rack'
gem 'rack-test'

if (RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", '1.2.5'
  gem "activerecord-jdbcsqlite3-adapter", '1.2.5'
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3-ruby"
end
