#!/usr/bin/env ruby

require 'yajl'
require 'httparty'

path = ARGV[0]
file = File.open(path)
parser = Yajl::Parser.new(:symbolize_keys => true)

client = HakoClient.new

parser.parse(file) do |results|
  results.each do |r|
    rsp = client.submit(r)
    puts "Got #{rsp.inspect}"
    puts "BODY = #{rsp.body}"
    exit 0
  end
end
