#!/usr/bin/env ruby

# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

puts 'waluigi'
require 'logger'
APP_PATH = File.expand_path('../rails_app/config/application', __dir__)
require_relative '../rails_app/config/boot'
require 'rails/command'
require_relative '../lib/performance'

Rails::Command.invoke(:runner, %w[Performance::Runner.new.run_and_report] + ARGV)
