name: 'Run Perfverse'
description: 'Runs performance testing on the specified agent tag'
inputs:
  agent_tags:
    description: 'JSON array of "git_tag:ENV_VAR_1=one;ENV_VAR_2=two" strings to run, one per tag'
    required: true
  iteration_index:
    description: 'Which iteration (matrix index) this job represents -- used to rotate agent_tags'
    required: true
  run_time:
    description: ''
    required: true
  nr_license_key:
    description: ''
    required: true
  test_tag:
    description: ''
    required: true
  docker_monitor_output_dir:
    description: ''
    required: true
    default: docker_monitor_output

runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # tag v1.315.0
      with:
        ruby-version: 3.4

    - name: Run ruby script
      shell: bash
      run: |
        ruby ./.github/workflows/scripts/run_perf_tests.rb
      env:
        AGENT_TAGS: ${{ inputs.agent_tags }}
        ITERATION_INDEX: ${{ inputs.iteration_index }}
        TEST_TAG: ${{ inputs.test_tag }}
        RUN_TIME: ${{ inputs.run_time }}
        NR_LICENSE_KEY: ${{ inputs.nr_license_key }}
        DOCKER_MONITOR_OUTPUT_DIR: ${{ inputs.docker_monitor_output_dir }}

    - name: Upload docker report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # tag v4.6.2
      with:
        if-no-files-found: error
        path: test/perfverse/docker_monitor/${{ inputs.docker_monitor_output_dir}}/
        name: docker_monitor_report-iteration_${{ inputs.iteration_index }}
        retention-days: 1

    - name: Upload locust report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # tag v4.6.2
      with:
        if-no-files-found: error
        path: test/perfverse/traffic/output/
        name: locust_report-iteration_${{ inputs.iteration_index }}
        retention-days: 1












