name: 'Build Ruby'
description: 'Builds the given Ruby version'
author: New Relic
inputs:
  ruby-version:
    description: 'Ruby version'
    required: true
    default: '2.7.6'
  dependencies:
    description: 'A list of ubuntu package names to install'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
