# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

require 'fileutils'
require 'tmpdir'

namespace :continuous_profiling do
  desc 'Regenerate the vendored OpenTelemetry profiles proto Ruby classes (requires system `protoc` with Ruby codegen support)'
  task :generate_proto do
    ContinuousProfilingProto.generate
  end
end

# Vendors New Relic's copy of the OpenTelemetry profiles proto files (opentelemetry-proto,
# Apache-2.0) as Ruby classes for ProfileEncoder, rather than depending on
# opentelemetry-exporter-otlp just for four generated files outside its public API.
#
# Generated files are post-processed to require_relative their dependencies (deterministic,
# independent of gem load order) and register through Proto::Registrar instead of
# Google::Protobuf directly -- see registrar.rb for why.
module ContinuousProfilingProto
  PROTO_DIR = File.expand_path('../new_relic/agent/continuous_profiling/proto', __dir__)

  LICENSE_HEADER = <<~HEADER
    # This file is distributed under New Relic's license terms.
    # See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
    # frozen_string_literal: true

  HEADER

  SOURCE_COMMENT = <<~COMMENT
    # Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
    # Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
    # Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto

  COMMENT

  # relative path (under PROTO_DIR) => fully-qualified name of one message defined in that
  # file, used to detect whether some other gem already registered the file first.
  ANCHOR_MESSAGE_BY_FILE = {
    'opentelemetry/proto/common/v1/common_pb.rb' => 'opentelemetry.proto.common.v1.AnyValue',
    'opentelemetry/proto/resource/v1/resource_pb.rb' => 'opentelemetry.proto.resource.v1.Resource',
    'opentelemetry/proto/profiles/v1development/profiles_pb.rb' =>
      'opentelemetry.proto.profiles.v1development.ProfilesDictionary',
    'opentelemetry/proto/collector/profiles/v1development/profiles_service_pb.rb' =>
      'opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest'
  }.freeze

  PROTO_FILES = %w[
    opentelemetry/proto/common/v1/common.proto
    opentelemetry/proto/resource/v1/resource.proto
    opentelemetry/proto/profiles/v1development/profiles.proto
    opentelemetry/proto/collector/profiles/v1development/profiles_service.proto
  ].freeze

  def self.generate
    Dir.mktmpdir do |tmp|
      PROTO_FILES.each { |relpath| FileUtils.cp(File.join(PROTO_DIR, relpath), File.join(tmp, relpath).tap { |p| FileUtils.mkdir_p(File.dirname(p)) }) }

      cmd = ['protoc', "-I#{tmp}", "--ruby_out=#{tmp}", *PROTO_FILES.map { |f| File.join(tmp, f) }]
      unless system(*cmd)
        puts 'Failed to generate proto files. Is `protoc` (with Ruby codegen support) installed?'
        return
      end

      ANCHOR_MESSAGE_BY_FILE.each_key { |relpath| postprocess(File.join(tmp, relpath), relpath) }
    end

    puts 'Continuous profiling proto files generated!'
  end

  def self.postprocess(generated_path, relpath)
    anchor = ANCHOR_MESSAGE_BY_FILE.fetch(relpath)
    lines = File.readlines(generated_path)
    lines.shift while lines.first&.start_with?('#')
    lines.shift while lines.first == "\n"

    depth = relpath.split('/').length - 1
    up = '../' * depth

    out = []
    lines.each do |line|
      case line
      when /^require 'google\/protobuf'\n?$/
        next # centralized in registrar.rb, required below
      when /^require '(opentelemetry\/proto\/.+_pb)'\n?$/
        out << "require_relative '#{up}#{Regexp.last_match(1)}'\n"
      when /^pool\.add_serialized_file\(descriptor_data\)\n?$/
        out << "NewRelic::Agent::ContinuousProfiling::Proto::Registrar.register_once(pool, descriptor_data, '#{anchor}')\n"
      else
        out << line
      end
    end
    out.unshift("require_relative '#{up}registrar'\n\n")

    File.write(File.join(PROTO_DIR, relpath), LICENSE_HEADER + SOURCE_COMMENT + out.join)
  end
end
