# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

require 'fileutils'
require 'tmpdir'

namespace :continuous_profiling do
  desc 'Regenerate the vendored OpenTelemetry profiles proto Ruby classes (requires system `protoc` with Ruby codegen support)'
  task :generate_proto do
    ContinuousProfilingProto.generate
  end
end

# Vendored (opentelemetry-proto, Apache-2.0) rather than depending on opentelemetry-exporter-otlp
# just for four generated files that sit outside its public API.
module ContinuousProfilingProto
  PROTO_DIR = File.expand_path('../new_relic/agent/continuous_profiling/proto', __dir__)

  # The package the vendored protos are rewritten to. Upstream's own package would collide in the
  # process-wide DescriptorPool with any opentelemetry-* gem shipping the same proto file names,
  # breaking whichever loaded second. protoc rubifies this to the namespace the classes live in.
  PACKAGE_PATH = 'new_relic/agent/continuous_profiling/proto'

  LICENSE_HEADER = <<~HEADER
    # This file is distributed under New Relic's license terms.
    # See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
    # frozen_string_literal: true

  HEADER

  SOURCE_COMMENT = <<~COMMENT
    # Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
    # Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
    # Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto
    # The vendored .proto sources differ from upstream only in their package and import paths.

  COMMENT

  PROTO_FILES = %w[
    common.proto
    resource.proto
    profiles.proto
    profiles_service.proto
  ].freeze

  def self.generate
    Dir.mktmpdir do |tmp|
      staged = PROTO_FILES.map do |basename|
        File.join(tmp, PACKAGE_PATH, basename).tap do |path|
          FileUtils.mkdir_p(File.dirname(path))
          FileUtils.cp(File.join(PROTO_DIR, basename), path)
        end
      end

      unless system('protoc', "-I#{tmp}", "--ruby_out=#{tmp}", *staged)
        puts 'Failed to generate proto files. Is `protoc` (with Ruby codegen support) installed?'
        return
      end

      PROTO_FILES.each do |basename|
        generated = basename.sub(/\.proto\z/, '_pb.rb')
        postprocess(File.join(tmp, PACKAGE_PATH, generated), generated)
      end
    end

    puts 'Continuous profiling proto files generated!'
  end

  def self.postprocess(generated_path, basename)
    lines = File.readlines(generated_path)
    lines.shift while lines.first&.start_with?('#')
    lines.shift while lines.first == "\n"

    File.write(File.join(PROTO_DIR, basename), LICENSE_HEADER + SOURCE_COMMENT + lines.join)
  end
end
