namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task :report do
    unless RUBY_VERSION >= '2.7.0'
      puts 'This task requires Ruby 2.7.0+'
      return
    end
    require 'simplecov'
    # FOR CI ONLY
    SimpleCov.collate Dir["coverage*/.resultset.json"]
  end
end
