namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task :report do
    require 'simplecov'
    # FOR CI ONLY
    SimpleCov.collate Dir["coverage*/.resultset.json"]
  end
end
