namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task :report do
    unless RUBY_VERSION >= '2.7.0'
      puts 'This task requires Ruby 2.7.0+'
      return
    end
    require 'simplecov'
    require 'simplecov_json_formatter'
    # FOR CI ONLY
    SimpleCov.collate Dir["coverage*/.resultset.json"] do
      formatter SimpleCov::Formatter::MultiFormatter.new([
        SimpleCov::Formatter::JSONFormatter,
        SimpleCov::Formatter::HTMLFormatter
      ])
      refuse_coverage_drop
    end
  end
end
