version: 2
updates:
  - package-ecosystem: npm
    directory: /.github/actions/annotate
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /.github/actions/simplecov-report
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /infinite_tracing
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/norails
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails40
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails41
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails42
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails50
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails51
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails52
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails60
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails61
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/rails70
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/environments/railsedge
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/performance
    schedule:
      interval: daily
