source 'https://rubygems.org'

gem "rails", "~>2.2.3"

gem 'rake', '~>10.1.1'
gem 'minitest', '~>4.7.5'
gem "mocha", :require => false
gem "jeweler", "1.4.0"
gem "rdoc"

gem 'rack'
gem 'rack-test'
gem 'newrelic_rpm', :path => '../../..'

if (RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", "~>1.2.9"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.2.9"
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3"
end

gem 'pry', '~> 0.9.12'
gem 'hometown', '~> 0.2.5'

gem 'git', '< 1.3' if RUBY_VERSION < '1.9' # git 1.3.0 requires Ruby version >= 1.9
