source 'http://rubygems.org'

gem "rails", "2.2.2"

gem "ci_reporter", "1.6.0"
gem "mocha", "0.9.8"
gem "jeweler", "1.4.0"
gem "gemcutter", "0.5.0"
gem "rdoc"

gem 'rack'
gem 'rack-test'
gem 'newrelic_rpm', :path => '../../..'

if (RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", "~>1.2.9"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.2.9"
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3"
  gem 'shoulda', '~> 3.0.0'
  gem 'sequel', '~> 3.46.0'
end
