# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rdoc/task'

gem 'newrelic_rpm'

require 'tasks/rails'
require 'tasks/all'

Rake::Task["default"].clear
task :default => [:'test:newrelic']
