# frozen_string_literal: true
brew 'elasticsearch'
brew 'imagemagick'
brew 'memcached'
tap 'mongodb/brew'
brew 'mongodb-community'
brew 'mysql'
brew 'openssl'
brew 'pkg-config'
brew 'postgresql'
brew 'rabbitmq'
brew 'redis'
