# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{newrelic_rpm}
  s.version = "2.12.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bill Kayser"]
  s.date = %q{2010-05-13}
  s.description = %q{New Relic RPM is a Ruby performance management system, developed by
New Relic, Inc (http://www.newrelic.com).  RPM provides you with deep
information about the performance of your Ruby on Rails or Merb
application as it runs in production. The New Relic Agent is
dual-purposed as a either a Rails plugin or a Gem, hosted on
http://github.com/newrelic/rpm/tree/master.
}
  s.email = %q{support@newrelic.com}
  s.executables = ["mongrel_rpm", "newrelic_cmd"]
  s.extra_rdoc_files = [
    "CHANGELOG",
     "LICENSE"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README.md",
     "bin/mongrel_rpm",
     "bin/newrelic_cmd",
     "cert/cacert.pem",
     "install.rb",
     "lib/new_relic/agent.rb",
     "lib/new_relic/agent/agent.rb",
     "lib/new_relic/agent/busy_calculator.rb",
     "lib/new_relic/agent/chained_call.rb",
     "lib/new_relic/agent/error_collector.rb",
     "lib/new_relic/agent/instrumentation/active_merchant.rb",
     "lib/new_relic/agent/instrumentation/active_record_instrumentation.rb",
     "lib/new_relic/agent/instrumentation/acts_as_solr.rb",
     "lib/new_relic/agent/instrumentation/authlogic.rb",
     "lib/new_relic/agent/instrumentation/controller_instrumentation.rb",
     "lib/new_relic/agent/instrumentation/data_mapper.rb",
     "lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb",
     "lib/new_relic/agent/instrumentation/memcache.rb",
     "lib/new_relic/agent/instrumentation/merb/controller.rb",
     "lib/new_relic/agent/instrumentation/merb/errors.rb",
     "lib/new_relic/agent/instrumentation/metric_frame.rb",
     "lib/new_relic/agent/instrumentation/net.rb",
     "lib/new_relic/agent/instrumentation/passenger_instrumentation.rb",
     "lib/new_relic/agent/instrumentation/rack.rb",
     "lib/new_relic/agent/instrumentation/rails/action_controller.rb",
     "lib/new_relic/agent/instrumentation/rails/action_web_service.rb",
     "lib/new_relic/agent/instrumentation/rails/errors.rb",
     "lib/new_relic/agent/instrumentation/rails3/action_controller.rb",
     "lib/new_relic/agent/instrumentation/rails3/errors.rb",
     "lib/new_relic/agent/instrumentation/sinatra.rb",
     "lib/new_relic/agent/instrumentation/sunspot.rb",
     "lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb",
     "lib/new_relic/agent/method_tracer.rb",
     "lib/new_relic/agent/sampler.rb",
     "lib/new_relic/agent/samplers/cpu_sampler.rb",
     "lib/new_relic/agent/samplers/delayed_job_lock_sampler.rb",
     "lib/new_relic/agent/samplers/memory_sampler.rb",
     "lib/new_relic/agent/samplers/object_sampler.rb",
     "lib/new_relic/agent/shim_agent.rb",
     "lib/new_relic/agent/stats_engine.rb",
     "lib/new_relic/agent/stats_engine/metric_stats.rb",
     "lib/new_relic/agent/stats_engine/samplers.rb",
     "lib/new_relic/agent/stats_engine/transactions.rb",
     "lib/new_relic/agent/transaction_sampler.rb",
     "lib/new_relic/agent/worker_loop.rb",
     "lib/new_relic/collection_helper.rb",
     "lib/new_relic/commands/deployments.rb",
     "lib/new_relic/commands/new_relic_commands.rb",
     "lib/new_relic/control.rb",
     "lib/new_relic/control/external.rb",
     "lib/new_relic/control/merb.rb",
     "lib/new_relic/control/rails.rb",
     "lib/new_relic/control/rails3.rb",
     "lib/new_relic/control/ruby.rb",
     "lib/new_relic/control/sinatra.rb",
     "lib/new_relic/delayed_job_injection.rb",
     "lib/new_relic/histogram.rb",
     "lib/new_relic/local_environment.rb",
     "lib/new_relic/merbtasks.rb",
     "lib/new_relic/metric_data.rb",
     "lib/new_relic/metric_parser.rb",
     "lib/new_relic/metric_parser/action_mailer.rb",
     "lib/new_relic/metric_parser/active_merchant.rb",
     "lib/new_relic/metric_parser/active_record.rb",
     "lib/new_relic/metric_parser/controller.rb",
     "lib/new_relic/metric_parser/controller_cpu.rb",
     "lib/new_relic/metric_parser/errors.rb",
     "lib/new_relic/metric_parser/external.rb",
     "lib/new_relic/metric_parser/mem_cache.rb",
     "lib/new_relic/metric_parser/other_transaction.rb",
     "lib/new_relic/metric_parser/view.rb",
     "lib/new_relic/metric_parser/web_frontend.rb",
     "lib/new_relic/metric_parser/web_service.rb",
     "lib/new_relic/metric_spec.rb",
     "lib/new_relic/metrics.rb",
     "lib/new_relic/noticed_error.rb",
     "lib/new_relic/rack/metric_app.rb",
     "lib/new_relic/rack/mongrel_rpm.ru",
     "lib/new_relic/rack/newrelic.yml",
     "lib/new_relic/rack_app.rb",
     "lib/new_relic/recipes.rb",
     "lib/new_relic/stats.rb",
     "lib/new_relic/transaction_analysis.rb",
     "lib/new_relic/transaction_sample.rb",
     "lib/new_relic/version.rb",
     "lib/new_relic_api.rb",
     "lib/newrelic_rpm.rb",
     "lib/tasks/all.rb",
     "lib/tasks/install.rake",
     "lib/tasks/tests.rake",
     "newrelic.yml",
     "newrelic_rpm.gemspec",
     "recipes/newrelic.rb",
     "test/active_record_fixtures.rb",
     "test/config/newrelic.yml",
     "test/config/test_control.rb",
     "test/new_relic/agent/active_record_instrumentation_test.rb",
     "test/new_relic/agent/agent_controller_test.rb",
     "test/new_relic/agent/agent_test_controller.rb",
     "test/new_relic/agent/busy_calculator_test.rb",
     "test/new_relic/agent/collection_helper_test.rb",
     "test/new_relic/agent/error_collector_test.rb",
     "test/new_relic/agent/memcache_instrumentation_test.rb",
     "test/new_relic/agent/method_tracer_test.rb",
     "test/new_relic/agent/metric_data_test.rb",
     "test/new_relic/agent/metric_frame_test.rb",
     "test/new_relic/agent/mock_ar_connection.rb",
     "test/new_relic/agent/mock_scope_listener.rb",
     "test/new_relic/agent/net_instrumentation_test.rb",
     "test/new_relic/agent/rpm_agent_test.rb",
     "test/new_relic/agent/stats_engine/metric_stats_test.rb",
     "test/new_relic/agent/stats_engine/samplers_test.rb",
     "test/new_relic/agent/stats_engine/stats_engine_test.rb",
     "test/new_relic/agent/task_instrumentation_test.rb",
     "test/new_relic/agent/testable_agent.rb",
     "test/new_relic/agent/transaction_sample_builder_test.rb",
     "test/new_relic/agent/transaction_sample_test.rb",
     "test/new_relic/agent/transaction_sampler_test.rb",
     "test/new_relic/agent/worker_loop_test.rb",
     "test/new_relic/control_test.rb",
     "test/new_relic/deployments_api_test.rb",
     "test/new_relic/environment_test.rb",
     "test/new_relic/metric_parser_test.rb",
     "test/new_relic/metric_spec_test.rb",
     "test/new_relic/shim_agent_test.rb",
     "test/new_relic/stats_test.rb",
     "test/new_relic/version_number_test.rb",
     "test/test_helper.rb",
     "test/ui/newrelic_controller_test.rb",
     "test/ui/newrelic_helper_test.rb",
     "ui/controllers/newrelic_controller.rb",
     "ui/helpers/google_pie_chart.rb",
     "ui/helpers/newrelic_helper.rb",
     "ui/views/layouts/newrelic_default.rhtml",
     "ui/views/newrelic/_explain_plans.rhtml",
     "ui/views/newrelic/_sample.rhtml",
     "ui/views/newrelic/_segment.rhtml",
     "ui/views/newrelic/_segment_limit_message.rhtml",
     "ui/views/newrelic/_segment_row.rhtml",
     "ui/views/newrelic/_show_sample_detail.rhtml",
     "ui/views/newrelic/_show_sample_sql.rhtml",
     "ui/views/newrelic/_show_sample_summary.rhtml",
     "ui/views/newrelic/_sql_row.rhtml",
     "ui/views/newrelic/_stack_trace.rhtml",
     "ui/views/newrelic/_table.rhtml",
     "ui/views/newrelic/explain_sql.rhtml",
     "ui/views/newrelic/images/arrow-close.png",
     "ui/views/newrelic/images/arrow-open.png",
     "ui/views/newrelic/images/blue_bar.gif",
     "ui/views/newrelic/images/file_icon.png",
     "ui/views/newrelic/images/gray_bar.gif",
     "ui/views/newrelic/images/new-relic-rpm-desktop.gif",
     "ui/views/newrelic/images/new_relic_rpm_desktop.gif",
     "ui/views/newrelic/images/textmate.png",
     "ui/views/newrelic/index.rhtml",
     "ui/views/newrelic/javascript/prototype-scriptaculous.js",
     "ui/views/newrelic/javascript/transaction_sample.js",
     "ui/views/newrelic/sample_not_found.rhtml",
     "ui/views/newrelic/show_sample.rhtml",
     "ui/views/newrelic/show_source.rhtml",
     "ui/views/newrelic/stylesheets/style.css",
     "ui/views/newrelic/threads.rhtml"
  ]
  s.homepage = %q{http://www.github.com/newrelic/rpm}
  s.post_install_message = %q{
Please see http://support.newrelic.com/faqs/docs/ruby-agent-release-notes
for a complete description of the features and enhancements available
in version 2.12 of the Ruby Agent.

For details on this specific release, refer to the CHANGELOG file.

}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source", "--title", "New Relic RPM"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{New Relic Ruby Performance Monitoring Agent}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

