configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    description: Ruby agent configuration
    type: AgentConfig
    version: 1.1.0
    schema: ./schemas/config.json
    format: yml
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: NRRubyAgent
        versions:
          - ">=9.24.0"
