# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rails', '~> 7.0.0.rc1'
gem "bootsnap", ">= 1.4.4", require: false

gem 'minitest', '5.2.3'
gem 'mocha', '~> 1.1.0', require: false

platforms :jruby do
  gem 'jruby-openssl'
end

platforms :ruby, :rbx do
  gem 'mysql2'
  gem 'sqlite3', '~> 1.4'
end

gem 'newrelic_rpm', path: '../../..'

gem 'hometown', '~> 0.2.5'
gem 'pry', '~> 0.12.2'
gem 'pry-nav'
