# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.3'

gem 'newrelic_rpm', '>= 8.8.0'

gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.2', '>= 7.0.2.3'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'

# https://github.com/rails/rails/issues/54260
# https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror
gem 'concurrent-ruby', '1.3.4'
