# This file is distributed under new relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/license for complete details.
# frozen_string_literal: true

require File.join(File.dirname(__FILE__), 'resque_setup')
require 'resque/tasks'
