source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'

gem 'rails', '5.0.0'

gem 'minitest', '5.2.3'
gem 'mocha', '~> 1.1.0', :require => false
gem 'rack', '< 2.1.0'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem "jruby-openssl"
end

platforms :ruby do
  gem "mysql2"
  gem 'sqlite3', '~> 1.3.13'
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.12.2'
gem 'pry-nav'
gem 'hometown', '~> 0.2.5'
