source 'https://rubygems.org'

gem 'rake', '< 11'

gem 'rails', '5.0.0beta3'

gem 'minitest', '5.2.3'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

platforms :jruby do
  gem "jruby-openssl"
end

platforms :ruby do
  gem "mysql2"
end

platforms :rbx do
  gem "rubysl"
  gem "json"
  # If we don't skip the require here, test-unit tries to install its at_exit
  # hook and run when we run our rake task to create the test DB.
  gem "rubysl-test-unit", :require => false
  gem "racc"  # https://github.com/rubinius/rubinius/issues/2632

  # Compilation issues with rubysl-openssl 2.2.1, lock at 2.1.0 for now.
  # https://github.com/rubysl/rubysl-openssl/issues/11
  gem "rubysl-openssl", "2.1.0"
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.9.12'
gem 'hometown', '~> 0.2.5'
