source 'https://rubygems.org'

gem 'rails', '~>3.2.20'
gem 'i18n', '0.6.11'

gem 'rake', '~>10.1.1'
gem 'minitest', '~>4.7.5'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

gem "newrelic_rpm", :path => "../../.."

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter"
  gem "activerecord-jdbcsqlite3-adapter"
  gem "jruby-openssl"
end

platforms :ruby, :rbx do
  gem "mysql", "~>2.9.1"
  gem "sqlite3"
end

gem 'pry', '~> 0.9.12'
gem 'hometown', '~> 0.2.5'

gem 'rack-cache', '< 1.3' if RUBY_VERSION < '1.9.3' # rack-cache 1.3.0 only supports >= 1.9.3
