source 'http://rubygems.org'

gem 'rake'

gem 'rails', '~>3.2.15'

gem "mocha", '~>0.13.0', :require => false
gem 'rack'
gem 'rack-test'

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter", "~>1.2.9"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.2.9"
  gem "jruby-openssl"
end

platforms :ruby, :rbx do
  gem "mysql", "~>2.9.1"
  gem "sqlite3"
end

gem "newrelic_rpm", :path => "../../.."
