# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative '../../warning_test_helper'
require_relative 'config/application'
require 'rake'

RpmTestApp::Application.load_tasks
require 'tasks/all'

Rake::Task["default"].clear
task :default => [:'test:newrelic_with_db']
task :'test:newrelic_with_db' => [:'db:create', :'test:newrelic']
