name: "SimpleCov Report"
description: "SimpleCov Report"
author: aki77
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold (line)
    default: "93.5"
    required: false
  failedThresholdBranch:
    description: Failed threshold (branch)
    default: "71.5"
    required: false
  resultPath:
    description: "json path"
    default: "coverage/.last_run.json"
    required: false
  token:
    description: "GitHub token"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
