name: 'Exec Tester'
description: 'Tests exec'
author: New Relic
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '3.1.0'
runs:
  using: 'node12'
  main: 'dist/index.js'
