#!/bin/bash

# RETRY_ATTEMPTS
# TEST_CMD

count=0
return_val=1

while [[ $return_val != 0  && $count -lt $RETRY_ATTEMPTS ]]; do
  $TEST_CMD
  return_val=$?
  count=$((count + 1))
  if [[ $return_val != 0 ]]; then
    echo $'\n*************************************************************************************************************\n'
    echo "FAILURE ON ATTEMPT $((count)) of $((RETRY_ATTEMPTS))"
    echo $'\n*************************************************************************************************************\n'
  else
    echo $'\n**************************Success on attempt $((count)) of $((RETRY_ATTEMPTS))*******************************\n'
  fi
done

exit $return_val