#!/bin/bash

# RETRY_ATTEMPTS
# TEST_CMD

echo "---1"
count=0
return_val=1

echo "---2"

while [[ $return_val != 0  && $count -lt $RETRY_ATTEMPTS ]]; do
  echo "---3"
  $TEST_CMD
  return_val=$?
  count=$((count + 1))
  echo "---4"
  if [[ $return_val != 0 ]]; then
    echo $'\n*************************************************************************************************************\n'
    echo "FAILURE ON ATTEMPT $((count)) of $((RETRY_ATTEMPTS))"
    echo $'\n*************************************************************************************************************\n'
  else
    echo $'\n**************************Success on attempt $((count)) of $((RETRY_ATTEMPTS))*******************************\n'
  fi
done

echo "---5"
exit $return_val