#!/bin/bash
# This script sets up the bundler versions we need for our older multiverse suites
# and sets up the bundler config for when we are using the older mysql version

if [[ $RUBY_VERSION =~ 2.[^67] ]]; then 
  # Older rubies come with older Rubygems and we need 3.0.6 to
  # correctly install Bundler 1.17.3 and do anything else within
  # the multiverse test suite
  # NOTE that Ruby 2.2 and 2.3 need to use update_rubygems, while
  # newer Rubies can use 'gem update --system'
  echo "DEBUG: RUBY_VERSION = $RUBY_VERSION"
  if [[ $RUBY_VERSION = "2.2.10" ]]; then
    echo "DEBUG: installing rubygems-update version 2.7.11"
    gem install rubygems-update:2.7.11
    echo "DEBUG: running 'rubygems-update'"
    update_rubygems
  else
    echo "DEBUG: running 'gem update --system --force'"
    gem update --system 3.0.6 --force
  fi
  echo "DEBUG: obtaining pre-installed Bundler version"
  og_bundler=$(bundle --version | awk '{ print $3 }')
  echo "DEBUG: pre-installed Bundler version is $og_bundler"
  if [[ "$og_bundler" != "1.17.3" ]]; then
    # need to use bundler <2 for all rails 4 and below tests
    echo "DEBUG: running 'gem install bundler'"
    gem install --default bundler:1.17.3 --force
    echo "DEBUG: running 'gem list bundler'"
    gem list bundler
    echo "DEBUG: RUBY_VERSION = $RUBY_VERSION"
    if [[ $RUBY_VERSION != "2.2.10" ]]; then 
      echo "DEBUG: running 'gem uninstall bundler'"
      gem uninstall bundler
      echo "DEBUG: running 'gem list bundler' again"
      gem list bundler
    fi
  fi
fi

# add mysql specific config for bundler when we are using older mysql
if [[ $RUBY_VERSION =~ 2.[23] ]]; then  
  echo "DEBUG: running 'bundle config'"
  bundle config --global build.mysql2 --with-mysql-config=/usr/local/mysql55/bin/mysql_config
  echo "set bundler to use mysql55 for mysql2"
fi

# for some reason, ruby 3.0 fails unless 3.1.0 is installed before it bundles for rails_prepend suite/rails 7
if [[ $RUBY_VERSION =~ 3.0 ]]; then 
  echo "DEBUG: running 'gem install digest'"
  gem install --default digest:3.1.0
  echo "installed digest 3.1.0"
fi

# for some reason, ruby 2.7+ fails unless strscan 3.0.4 is installed
if [[ $RUBY_VERSION = 3.* || $RUBY_VERSION =~ 2.7 ]]; then 
  echo "DEBUG: running 'gem install strscan'"
  gem install --default strscan:3.0.4
  echo "installed strscan 3.0.4"

  echo "DEBUG: running gem install set"
  gem install --default set:1.0.3
  echo "installed set 1.0.3"
fi

echo "DEBUG: running 'bundle install'"
bundle install
