# frozen_string_literal: true
source 'https://rubygems.org'

gem 'newrelic_rpm', :path => '../../..'

gem 'mocha'
gem 'pry'
gem 'pry-nav'
gem 'rack'
gem 'rack/handler'
gem 'redis'
gem 'stackprof'
gem 'webrick' if RUBY_VERSION >= '3.0'
