# frozen_string_literal: true

source 'https://rubygems.org'

gem 'newrelic_rpm', path: File.expand_path('../../..', __FILE__)

gem 'rails', '~> 8.0'
gem 'puma'
gem 'sqlite3'

gem 'mocha'
gem 'redis'
gem 'simplecov'
gem 'stackprof'
gem 'webrick' if RUBY_VERSION >= '3.0'

gem 'logger'
