# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
# Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
# Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto

require_relative '../../../../registrar'


require_relative '../../../../opentelemetry/proto/common/v1/common_pb'


descriptor_data = "\n.opentelemetry/proto/resource/v1/resource.proto\x12\x1fopentelemetry.proto.resource.v1\x1a*opentelemetry/proto/common/v1/common.proto\"\xa8\x01\n\x08Resource\x12;\n\nattributes\x18\x01 \x03(\x0b\x32\'.opentelemetry.proto.common.v1.KeyValue\x12 \n\x18\x64ropped_attributes_count\x18\x02 \x01(\r\x12=\n\x0b\x65ntity_refs\x18\x03 \x03(\x0b\x32(.opentelemetry.proto.common.v1.EntityRefB\x83\x01\n\"io.opentelemetry.proto.resource.v1B\rResourceProtoP\x01Z*go.opentelemetry.io/proto/otlp/resource/v1\xaa\x02\x1fOpenTelemetry.Proto.Resource.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
NewRelic::Agent::ContinuousProfiling::Proto::Registrar.register_once(pool, descriptor_data, 'opentelemetry.proto.resource.v1.Resource')

module Opentelemetry
  module Proto
    module Resource
      module V1
        Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.resource.v1.Resource").msgclass
      end
    end
  end
end
