require 'rake/testtask.rb'
require File.join(File.dirname(__FILE__),'lib','multiverse','color')

desc "Test the testing framework by executing tests in /test. Get meta with it."
task "test:self" do
  extend Multiverse::Color
  puts yellow("Testing the multiverse testing framework...")
  test_files = FileList['test/*_test.rb']
  ruby test_files.join(" ")
end

desc "Test the agent. Run all suites in /suites to test."
task "test" do
  ruby 'script/runner'
end

task 'default' => ['test:self', 'test']
