# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 7.0.4'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', require: false

platforms :ruby, :rbx do
  gem 'mysql2', '>= 0.5.4'
  gem 'sqlite3', '~> 1.4'
end

gem 'newrelic_rpm', path: '../../..'
gem 'newrelic_security', path: '../../../vendor/newrelic_security', require: false

gem 'pry', '~> 0.14.1'
gem 'pry-nav'
gem 'simplecov' if ENV['VERBOSE_TEST_OUTPUT']
gem 'warning' if RUBY_VERSION >= '2.4.0'
