# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 7.0.4'
gem 'bootsnap', '>= 1.4.4', require: false

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', require: false

platforms :ruby, :rbx do
  gem 'mysql2', '>= 0.5.4'
  gem 'sqlite3', '~> 1.4'
end

gem 'newrelic_rpm', path: '../../..'

gem 'pry' if ENV['ENABLE_PRY']

gem 'simplecov' if ENV['VERBOSE_TEST_OUTPUT']
gem 'warning'

# i18n 1.15.0+ is broken on Ruby 3.1 and will not be fixed, so pin below it
if RUBY_VERSION.start_with?('3.1.')
  gem 'i18n', '< 1.15.0'
end

if RUBY_VERSION.split('.')[0..1].join('.').to_f >= 3.4
  gem 'base64'
  gem 'bigdecimal'
  gem 'mutex_m'
  gem 'ostruct'
  gem 'benchmark'
end
gem 'logger'
