source 'http://rubygems.org'

gem 'rails', '~>3.1.12'
gem 'newrelic_rpm', :path => '../../..'
gem 'minitest', '~>4.7.5'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

if (RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", "~>1.2.9"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.2.9"
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3-ruby"
end
