
# A wrapper around the google charts service.
# TODO consider making generic and open sourcing
class GooglePieChart
  attr_accessor :width, :height, :color

  def initialize
    # an array of [label, value]
    @data = []

    self.width = 300
    self.height = 200
  end

  def add_data_point(label, value)
    @data << [label, value]
    @max = (@max.nil? || @max < value ? value : @max)
  end

  # render the chart to html by creating an image object and
  # placing the correct URL to the google charts api
  def render
    labels = ''
    values = ''
    @data.each do |label, value|
      labels << CGI::escape(label) + '|'
      values << (value * 100 / @max).round.to_s + ","
    end

    # strip of the last separator char for labels and values
    labels = labels[0..-2]
    values = values[0..-2]

    @url = "http://chart.apis.google.com/chart?"
    param "cht", "p"
    param "chco", color if color
    param "chs", "#{width}x#{height}"
    param "chd", "t:#{values}"
    param "chl", labels    

    alt_msg = "This pie chart is generated by Google Charts. You must be connected to the Internet to view this chart."
    html = "<img src=#{@url} alt=\"#{alt_msg}\"/>"
    return html       
  end

private 
  def param(key,value)
    if @not_first_param
      @url += "&amp;"
    else
      @not_first_param = true
    end
    @url += "#{key}=#{value}"
  end
end
