# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
# Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
# Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto
# The vendored .proto sources differ from upstream only in their package and import paths.

require 'google/protobuf'


descriptor_data = "\n7new_relic/agent/continuous_profiling/proto/common.proto\x12*new_relic.agent.continuous_profiling.proto\"\xc7\x02\n\x08\x41nyValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12M\n\x0b\x61rray_value\x18\x05 \x01(\x0b\x32\x36.new_relic.agent.continuous_profiling.proto.ArrayValueH\x00\x12P\n\x0ckvlist_value\x18\x06 \x01(\x0b\x32\x38.new_relic.agent.continuous_profiling.proto.KeyValueListH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x12\x1f\n\x15string_value_strindex\x18\x08 \x01(\x05H\x00\x42\x07\n\x05value\"R\n\nArrayValue\x12\x44\n\x06values\x18\x01 \x03(\x0b\x32\x34.new_relic.agent.continuous_profiling.proto.AnyValue\"T\n\x0cKeyValueList\x12\x44\n\x06values\x18\x01 \x03(\x0b\x32\x34.new_relic.agent.continuous_profiling.proto.KeyValue\"r\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x43\n\x05value\x18\x02 \x01(\x0b\x32\x34.new_relic.agent.continuous_profiling.proto.AnyValue\x12\x14\n\x0ckey_strindex\x18\x03 \x01(\x05\"\xa1\x01\n\x14InstrumentationScope\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12H\n\nattributes\x18\x03 \x03(\x0b\x32\x34.new_relic.agent.continuous_profiling.proto.KeyValue\x12 \n\x18\x64ropped_attributes_count\x18\x04 \x01(\r\"X\n\tEntityRef\x12\x12\n\nschema_url\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07id_keys\x18\x03 \x03(\t\x12\x18\n\x10\x64\x65scription_keys\x18\x04 \x03(\tB{\n io.opentelemetry.proto.common.v1B\x0b\x43ommonProtoP\x01Z(go.opentelemetry.io/proto/otlp/common/v1\xaa\x02\x1dOpenTelemetry.Proto.Common.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module NewRelic
  module Agent
    module ContinuousProfiling
      module Proto
        AnyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.AnyValue").msgclass
        ArrayValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.ArrayValue").msgclass
        KeyValueList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.KeyValueList").msgclass
        KeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.KeyValue").msgclass
        InstrumentationScope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.InstrumentationScope").msgclass
        EntityRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.EntityRef").msgclass
      end
    end
  end
end
