# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
# Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
# Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto
# The vendored .proto sources differ from upstream only in their package and import paths.

require 'google/protobuf'

require 'new_relic/agent/continuous_profiling/proto/profiles_pb'


descriptor_data = "\nAnew_relic/agent/continuous_profiling/proto/profiles_service.proto\x12*new_relic.agent.continuous_profiling.proto\x1a\x39new_relic/agent/continuous_profiling/proto/profiles.proto\"\xcb\x01\n\x1c\x45xportProfilesServiceRequest\x12W\n\x11resource_profiles\x18\x01 \x03(\x0b\x32<.new_relic.agent.continuous_profiling.proto.ResourceProfiles\x12R\n\ndictionary\x18\x02 \x01(\x0b\x32>.new_relic.agent.continuous_profiling.proto.ProfilesDictionary\"\x82\x01\n\x1d\x45xportProfilesServiceResponse\x12\x61\n\x0fpartial_success\x18\x01 \x01(\x0b\x32H.new_relic.agent.continuous_profiling.proto.ExportProfilesPartialSuccess\"P\n\x1c\x45xportProfilesPartialSuccess\x12\x19\n\x11rejected_profiles\x18\x01 \x01(\x03\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xb3\x01\n\x0fProfilesService\x12\x9f\x01\n\x06\x45xport\x12H.new_relic.agent.continuous_profiling.proto.ExportProfilesServiceRequest\x1aI.new_relic.agent.continuous_profiling.proto.ExportProfilesServiceResponse\"\x00\x42\xc9\x01\n7io.opentelemetry.proto.collector.profiles.v1developmentB\x14ProfilesServiceProtoP\x01Z?go.opentelemetry.io/proto/otlp/collector/profiles/v1development\xaa\x02\x34OpenTelemetry.Proto.Collector.Profiles.V1Developmentb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module NewRelic
  module Agent
    module ContinuousProfiling
      module Proto
        ExportProfilesServiceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.ExportProfilesServiceRequest").msgclass
        ExportProfilesServiceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.ExportProfilesServiceResponse").msgclass
        ExportProfilesPartialSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.ExportProfilesPartialSuccess").msgclass
      end
    end
  end
end
