# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Generated by protoc --ruby_out from vendored OpenTelemetry proto sources.
# Do not hand-edit; regenerate via `rake continuous_profiling:generate_proto`.
# Source: opentelemetry-proto (Apache-2.0) https://github.com/open-telemetry/opentelemetry-proto
# The vendored .proto sources differ from upstream only in their package and import paths.

require 'google/protobuf'

require 'new_relic/agent/continuous_profiling/proto/common_pb'


descriptor_data = "\n9new_relic/agent/continuous_profiling/proto/resource.proto\x12*new_relic.agent.continuous_profiling.proto\x1a\x37new_relic/agent/continuous_profiling/proto/common.proto\"\xc2\x01\n\x08Resource\x12H\n\nattributes\x18\x01 \x03(\x0b\x32\x34.new_relic.agent.continuous_profiling.proto.KeyValue\x12 \n\x18\x64ropped_attributes_count\x18\x02 \x01(\r\x12J\n\x0b\x65ntity_refs\x18\x03 \x03(\x0b\x32\x35.new_relic.agent.continuous_profiling.proto.EntityRefB\x83\x01\n\"io.opentelemetry.proto.resource.v1B\rResourceProtoP\x01Z*go.opentelemetry.io/proto/otlp/resource/v1\xaa\x02\x1fOpenTelemetry.Proto.Resource.V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module NewRelic
  module Agent
    module ContinuousProfiling
      module Proto
        Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("new_relic.agent.continuous_profiling.proto.Resource").msgclass
      end
    end
  end
end
