# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'
gem 'rails', '~> 6.1.7'

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', require: false
gem 'rack'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter', '~> 61.0'
  gem 'activerecord-jdbcsqlite3-adapter', '~> 61.0'
end

platforms :ruby, :rbx do
  gem 'mysql2'
  if RUBY_VERSION < '2.6'
    gem 'sqlite3', '~> 1.4.0'
  elsif RUBY_VERSION < '2.7'
    gem 'sqlite3', '< 1.6'
  else
    gem 'sqlite3', '< 2'
  end
end

gem 'newrelic_rpm', path: '../../..'

gem 'pry' if ENV['ENABLE_PRY']

gem 'simplecov' if ENV['VERBOSE_TEST_OUTPUT']
gem 'warning'

# i18n 1.15.0+ is broken on Ruby 3.1 and will not be fixed, so pin below it
if RUBY_VERSION.start_with?('3.1.')
  gem 'i18n', '< 1.15.0'
end

if RUBY_VERSION.split('.')[0..1].join('.').to_f >= 3.4
  gem 'base64'
  gem 'bigdecimal'
  gem 'mutex_m'
  gem 'ostruct'
  gem 'benchmark'
end

gem 'logger'
