# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'

gem 'rails', '~> 6.0.6'

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', :require => false
gem 'rack'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter', '~> 60.0'
  gem 'activerecord-jdbcsqlite3-adapter', '~> 60.0'
end

platforms :ruby, :rbx do
  gem 'mysql2', '>= 0.5.4'
  if RUBY_VERSION < '2.6'
    gem 'sqlite3', '~> 1.4.0'
  elsif RUBY_VERSION < '2.7'
    gem 'sqlite3', '~> 1.5.4'
  else
    gem 'sqlite3'
  end
end

gem 'newrelic_rpm', :path => '../../..'

group :development do
  if ENV['ENABLE_PRY']
    gem 'pry', '~> 0.9.12'
    gem 'pry-nav'
  end
end

gem 'simplecov' if ENV['VERBOSE_TEST_OUTPUT']
gem 'warning'
