source 'https://rubygems.org'

gem 'rake', '< 11'

gem 'rails', '6.0.0.beta3'

gem 'minitest', '5.2.3'
gem 'mocha', '~> 1.9.0', :require => false
gem 'rack'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem "jruby-openssl"
end

platforms :ruby do
  gem "mysql2"
  gem 'sqlite3', '~> 1.3.13'
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.9.12'
gem 'pry-nav'
gem 'hometown', '~> 0.2.5'
