source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'

gem 'rails', '~> 6.0.0'

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.1.0', :require => false
gem 'rack', '>= 2.1.4'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem "jruby-openssl"
  gem "activerecord-jdbcmysql-adapter", "~> 60.0"
  gem "activerecord-jdbcsqlite3-adapter", "~> 60.0"
end

platforms :ruby, :rbx do
  gem "mysql2", '>= 0.5.4'
  gem 'sqlite3', '~> 1.4'
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.14.1'
gem 'pry-nav'
