# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: infinite_tracing.proto for package 'com.newrelic.trace.v1'

require 'grpc'
require 'infinite_tracing_pb'

module Com
  module Newrelic
    module Trace
      module V1
        module IngestService
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'com.newrelic.trace.v1.IngestService'

            # Accepts a stream of Span messages, and returns an irregular stream of
            # RecordStatus messages.
            rpc :RecordSpan, stream(Span), stream(RecordStatus)
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
