# This file is distributed under new relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/license for complete details.
# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,

require_relative '../../warning_test_helper'

require_relative 'config/application'
require 'rake'

RpmTestApp::Application.load_tasks
require 'tasks/all'

Rake::Task['default'].clear
task :default => [:'test:newrelic']
