require File.expand_path('config/database')

desc "Setup for ActiveRecord"
task :environment do
  # MySql 5.7 and later no longer support NULL in primary keys
  # This overrides the default definition mysql2 adapter emits
  # to remove the NULL keyword from the PK declaration.
  class ::ActiveRecord::ConnectionAdapters::Mysql2Adapter
    NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
  end

  if defined?(DatabaseTasks)
    ActiveRecord::Base.configurations = DatabaseTasks.database_configuration
    ActiveRecord::Base.establish_connection DatabaseTasks.env.to_sym
  end
end
