# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'

gem 'minitest', "#{RUBY_VERSION >= '2.7.0' ? '5.3.3' : '4.7.5'}"
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', :require => false
gem 'rack'
gem 'rack-test', '< 0.8.0'

gem 'newrelic_rpm', :path => '../../..'

gem 'pry' if ENV['ENABLE_PRY']

if ENV['VERBOSE_TEST_OUTPUT']
  gem 'simplecov'
  # simplecov >= 1.0 requires prism, which doesn't come with JRuby 10+
  gem 'prism' if RUBY_ENGINE == 'jruby' && Gem::Version.new(JRUBY_VERSION) >= Gem::Version.new('10.0.0')
end

gem 'warning'

if RUBY_VERSION.split('.')[0..1].join('.').to_f >= 3.4
  gem 'mutex_m'
  gem 'ostruct'
end
