source 'http://rubygems.org'

gem 'rake'

gem 'minitest'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

platforms :rbx do
  gem "rubysl"
  gem "rubysl-test-unit"
  gem "psych"
  gem "racc"  # https://github.com/rubinius/rubinius/issues/2632
end

gem "newrelic_rpm", :path => "../../.."
