source 'https://rubygems.org'

gem 'rake'

gem "mocha", '~>0.13.0', :require => false
gem 'rack'
gem 'rack-test'

platforms :rbx do
  gem "rubysl"
  gem "rubysl-test-unit"
  gem "json"
  gem "psych"
  gem "racc"  # https://github.com/rubinius/rubinius/issues/2632
end

gem "newrelic_rpm", :path => "../../.."
