# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rake'
require 'tasks/all'

ENV["NO_RAILS"] = "1"

task :default => [:'test:newrelic']
