# This file is distributed under New Relic's license terms.
# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,

require_relative '../../warning_test_helper'

require 'rake'
require 'tasks/all'

ENV['NO_RAILS'] = '1'

task :default => [:'test:newrelic']
