source 'https://rubygems.org'

gem "test-unit"

gem "rails", "~> 2.3.18"

gem "mocha", "0.9.8"
gem 'rack'
gem 'rack-test'
gem 'rdoc'

gem "newrelic_rpm", :path => '../../..'

if(RUBY_PLATFORM == 'java')
  gem "activerecord-jdbcmysql-adapter", "~>1.2.9"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.2.9"
  gem "jruby-openssl"
else
  gem "mysql", "~>2.9.1"
  gem "sqlite3-ruby", "1.2.5"
end
