# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rails', git: 'https://github.com/rails/rails.git', branch: 'main'
gem "bootsnap", ">= 1.4.4", require: false

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.1.0', require: false

platforms :jruby do
  gem 'jruby-openssl'
end

platforms :ruby, :rbx do
  gem 'mysql2', '>= 0.5.4'
  gem 'sqlite3', '~> 1.4'
end

gem 'newrelic_rpm', path: '../../..'

gem 'pry', '~> 0.14.1'
gem 'pry-nav'
