source 'http://rubygems.org'

gem 'rake'

gem 'rails', '~>4.0.0'

gem "mocha", '~>0.13.0', :require => false
gem 'rack'
gem 'rack-test'

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter", "~>1.3.0"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.3.0"
  gem "jruby-openssl"
end

platforms :mri_19, :mri_20, :rbx do
  gem "mysql"
  gem "sqlite3-ruby"
  gem "sqlite3"
end

platforms :rbx do
  gem "rubysl"
  gem "racc"  # https://github.com/rubinius/rubinius/issues/2632
end

gem "newrelic_rpm", :path => "../../.."
