source 'https://rubygems.org'

gem 'rails', '~>4.0.13'
gem 'rake', '~> 12.3.3'

gem 'minitest', '~>4.7.5', require: false
gem 'mocha', '~> 1.9.0', require: false
gem 'rack-test'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter', '~>1.3.0'
  gem 'activerecord-jdbcsqlite3-adapter', '~>1.3.0'
  gem 'jruby-openssl'
end

platforms :ruby, :rbx do
  gem 'mysql2', '~> 0.3.20'
  gem 'sqlite3', '~> 1.3.13'
end

gem 'newrelic_rpm', path: '../../..'

gem 'hometown', '~> 0.2.5'
gem 'pry', '~> 0.9.12'
