source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'

gem 'rails', '4.2.11'

gem 'minitest', '5.2.3'
gem 'mocha', '~> 1.1.0', :require => false
gem 'rack', '< 2.0.0'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter", "~>1.3.0"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.3.0"
  gem "jruby-openssl"
end

platforms :ruby do
  gem "mysql2"
  gem 'sqlite3', '~> 1.3.13'
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.12.2'
gem 'pry-nav'
gem 'hometown', '~> 0.2.5'
gem 'nokogiri', '< 1.7' if RUBY_VERSION < '2.1.0' # nokogiri 1.7.0 only supports >= 2.1.0
