name: 'Set up mysql'
description: 'set up and cache mysql for tests'
inputs:
  ruby-version:
    description: 'What ruby version to install'
    required: true

runs:
  using: "composite"
  steps:
    - name: Wait for/Check Mysql
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # tag v4.0.0
      with:
        timeout_minutes: 1
        max_attempts: 20
        command: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'";
          if [[ $? != 0 ]]; then
            sleep 1;
          fi

