# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '~> 12.3.3'
gem 'rails', '~> 5.1.0'

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', :require => false
gem 'rack'
gem 'rack-test'
gem 'sprockets', '3.7.2'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter', '~> 51.0'
  gem 'activerecord-jdbcsqlite3-adapter', '~> 51.0'
end

platforms :ruby, :rbx do
  gem 'mysql2'
  gem 'sqlite3', '~> 1.3.13'
end

gem 'newrelic_rpm', :path => '../../..'

gem 'pry' if ENV['ENABLE_PRY']

gem 'warning'
