# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '10.0.4'
gem 'rails', '~> 4.1.0'

gem 'minitest', '5.2.3'
gem 'minitest-stub-const', '~> 0.6'
gem 'mocha', '~> 1.16', :require => false
gem 'rack', '~> 1.5.2'
gem 'rack-test'

platforms :jruby do
  gem 'activerecord-jdbcmysql-adapter', '~>1.3.0'
  gem 'activerecord-jdbcsqlite3-adapter', '~>1.3.0'
end

platforms :ruby do
  gem 'mysql2', '~> 0.3.20'
  gem 'sqlite3', '~> 1.3.13'
end

gem 'newrelic_rpm', :path => '../../..'

gem 'pry' if ENV['ENABLE_PRY']

gem 'warning'
