source 'https://rubygems.org'

gem 'rake', '< 11'

gem 'rails', '~>4.1.10'

# mime-types 2.99.1 and 3.x introduce mime-types-data
# mime-types-data requires Ruby version >= 2.0
# mime-types 2.99 requires Ruby version >= 1.9.3
if RUBY_VERSION < '1.9.3'
  gem 'mime-types', '1.25.1'
elsif RUBY_VERSION < '2'
  gem 'mime-types', '< 3'
end

gem 'minitest', '5.2.3'
gem 'mocha', :require => false
gem 'rack'
gem 'rack-test'

platforms :jruby do
  gem "activerecord-jdbcmysql-adapter", "~>1.3.0"
  gem "activerecord-jdbcsqlite3-adapter", "~>1.3.0"
  gem "jruby-openssl"
end

platforms :ruby do
  gem "mysql2", '~> 0.3.20'
  gem "sqlite3"
end

platforms :rbx do
  gem "rubysl"
  gem "json"
  # If we don't skip the require here, test-unit tries to install its at_exit
  # hook and run when we run our rake task to create the test DB.
  gem "rubysl-test-unit", :require => false
  gem "racc"  # https://github.com/rubinius/rubinius/issues/2632
end

gem "newrelic_rpm", :path => "../../.."

gem 'pry', '~> 0.9.12'
gem 'hometown', '~> 0.2.5'
