name: Add new issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # tag 2.0.0
        with:
          project-url: https://github.com/orgs/newrelic/projects/84
          github-token: ${{ secrets.NEW_RELIC_RUBY_AGENT_BOT_GITHUB_ADD_TO_PROJECT_ACTION }}
