name: Label community issues and pr

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  check_contributor_handle:
    runs-on: ubuntu-latest
    steps:
      - name: Label community issue
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # tag v9.0.0
        with:
         script: |
           github.rest.issues.addLabels({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             labels: ['community']
           })
        if: |
          github.event.issue.user.login != 'newrelic-ruby-agent-bot' && github.event.issue.user.login != 'kaylareopelle' && github.event.issue.user.login != 'tannalynn' && github.event.issue.user.login != 'chynesNR' && github.event.issue.user.login != 'elucus' && github.event.issue.user.login != 'hannahramadan' &&
          github.event.pull_request.user.login != 'newrelic-ruby-agent-bot' && github.event.pull_request.user.login != 'kaylareopelle' && github.event.pull_request.user.login != 'tannalynn' && github.event.pull_request.user.login != 'chynesNR' && github.event.pull_request.user.login != 'elucus' && github.event.pull_request.user.login != 'hannahramadan'
