name: Create Release PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  create_prerelease_tag:
    if: ${{ ((github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'prerelease'))) || (github.event_name == 'workflow_dispatch') }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
    - name: Install Ruby 3.4
      uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # tag v1.287.0
      with:
        ruby-version: 3.4

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag v6.0.2

    - run: bundle install

    - name: Set prerelease tag env var
      run: echo "prerelease_tag=$(bundle exec rake newrelic:version:current)-pre" >> $GITHUB_ENV

    - name: Make tag
      uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # tag v2.6.1
      with:
        tag_name: ${{ env.prerelease_tag }}
        name: ${{ env.prerelease_tag }}
        target_commitish: dev
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
