name: Create Prerelease

on:
  workflow_dispatch:

jobs:
  create_prerelease:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Install Ruby 4.0
      uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # tag v1.306.0
      with:
        ruby-version: 4.0

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag v6.0.2

    - run: bundle install

    - name: Update files with new version
      run: bundle exec rake newrelic:version:bump

    - name: Update newrelic.yml
      run: bundle exec rake newrelic:update_newrelicyml

    - name: Set tag name
      run: echo "prerelease_tag=$(bundle exec rake newrelic:version:current)-pre" >> $GITHUB_ENV

    - name: Push branch and create pull request
      run: |
        git checkout -b "prerelease_updates_${{ env.prerelease_tag }}"
        git add --all
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name 'newrelic-ruby-agent-bot'
        git commit -m "bump version"
        git push --set-upstream origin "prerelease_updates_${{ env.prerelease_tag }}"
        PR_URL=$(gh pr create --title "$TITLE" --body "$BODY")
        echo "pr_url=$PR_URL" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.NEWRELIC_RUBY_AGENT_BOT_TOKEN }}
        TITLE: "Prerelease ${{env.prerelease_tag}}"
        BODY: "Updates the version number, changelog, and newrelic.yml (if it needs updating). This is an automated PR."

    - name: Add label to pull request
      run: gh pr edit "${{ env.pr_url }}" --add-label prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}