name: Create Release PR

on:
  pull_request:
    types:
      - closed

jobs:
  create_release_pr:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'prerelease')) }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Install Ruby 3.4
      uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # tag v1.315.0
      with:
        ruby-version: 3.4

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag v7.0.1

    - run: bundle install

    - name: Set agent version
      run: echo "agent_version=$(bundle exec rake newrelic:version:current)" >> $GITHUB_ENV

    - name: Create pull request
      run: gh pr create --draft --base "main" --title "$TITLE" --body "$BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TITLE: "Release ${{ env.agent_version }}"
        BODY: "Automated PR for ${{ env.agent_version}} release"
