name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      agent_version: ${{ steps.version.outputs.VERSION }}
    permissions:
      contents: write
      repository-projects: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag v7.0.0
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # tag v1.310.0
      with:
        ruby-version: 3.4

    - name: Install onetimepass
      run: pip install onetimepass==1.0.1

    - name: Configure gem credentials
      run: |
        echo "GEM_HOST_API_KEY=${{ secrets.RUBYGEMS_API_KEY }}" >> $GITHUB_ENV
        echo "RUBYGEMS_MFA_KEY=${{ secrets.RUBYGEMS_MFA_KEY }}" >> $GITHUB_ENV

    - name: Build newrelic_rpm gem
      run: gem build newrelic_rpm.gemspec

    - name: Build newrelic-infinite_tracing gem
      run: |
        cd infinite_tracing
        gem build newrelic-infinite_tracing.gemspec
        cd ..

    - name: Determine version
      id: version
      run: |
        echo "VERSION=$(ls newrelic_rpm-*.gem | ruby -pe 'sub(/newrelic_rpm\-(.*).gem/, "\\1")')" >> $GITHUB_ENV
        echo "VERSION=$(ls newrelic_rpm-*.gem | ruby -pe 'sub(/newrelic_rpm\-(.*).gem/, "\\1")')" >> $GITHUB_OUTPUT

    - name: Create github release
      uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # tag v3.0.1
      if: $(git tag -l ${{ env.VERSION }}) == false
      with:
        tag_name: ${{ env.VERSION }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Obtain OTP to publish newrelic_rpm to rubygems.org
      run: echo "RUBYGEMS_OTP=$(python ./.github/workflows/scripts/rubygems-authenticate.py RUBYGEMS_MFA_KEY)" >> $GITHUB_ENV

    - name: Publish newrelic_rpm to rubygems.org
      run: ruby ./.github/workflows/scripts/rubygems-publish.rb newrelic_rpm

    - name: Obtain OTP to publish newrelic-infinite_tracing to rubygems.org
      run: echo "RUBYGEMS_OTP=$(python ./.github/workflows/scripts/rubygems-authenticate.py RUBYGEMS_MFA_KEY)" >> $GITHUB_ENV

    - name: Publish newrelic-infinite_tracing to rubygems.org
      run: ruby ./.github/workflows/scripts/rubygems-publish.rb infinite_tracing/newrelic-infinite_tracing

  update-agent-metadata:
    needs: [release]
    permissions:
      contents: read
    uses: ./.github/workflows/agent_metadata.yml
    with:
      version: ${{ needs.release.outputs.agent_version }}
    secrets:
      FC_SYS_ID_CLIENT_ID: ${{ secrets.FC_SYS_ID_CLIENT_ID }}
      FC_SYS_ID_PR_KEY: ${{ secrets.FC_SYS_ID_PR_KEY }}
      APM_CONTROL_NR_LICENSE_KEY_STAGING: ${{ secrets.APM_CONTROL_NR_LICENSE_KEY_STAGING }}
