name: Slack Notifications

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  gem_notifications:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # tag v1.310.0
        with:
          ruby-version: 3.4
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag v6.0.3
      - run: gem install httparty
      - name: Check for outdated gems
        run: ruby .github/workflows/scripts/slack_notifications/gem_notifier.rb
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_API_ENDPOINT: ${{ secrets.CLAUDE_API_ENDPOINT }}
