name: Slack Notifications

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  gem_notifications:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # tag v1.321.0
        with:
          ruby-version: 3.4
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag v7.0.1
      - run: gem install httparty
      - name: Check for outdated gems
        run: ruby .github/workflows/scripts/slack_notifications/gem_notifier.rb
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_API_ENDPOINT: ${{ secrets.CLAUDE_API_ENDPOINT }}
