name: Slack Notifications

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  gem_notifications:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # tag v1.315.0
        with:
          ruby-version: 3.4
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag v7.0.0
      - run: gem install httparty
      - name: Check for outdated gems
        run: ruby .github/workflows/scripts/slack_notifications/gem_notifier.rb
        env:
          SLACK_GEM_NOTIFICATIONS_WEBHOOK: ${{ secrets.SLACK_GEM_NOTIFICATIONS_WEBHOOK }}
