name: Check Spelling

on:
  pull_request:

jobs:
  spelling-check:
    name: SPELLING check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          # Files should be consistent with check:spelling files
          files: |
            **/*.md
          config: .cspell.yml
          